{{ if and .Values.secret .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  annotations:
    "helm.sh/resource-policy": keep
type: generic
data:
  POSTGRES_USER: {{ "postgres" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ randAlphaNum 64 | b64enc | quote }}
{{ end }}