apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  ports:
  - port: 5432
    protocol: TCP
    name: {{ .Release.Name }}
    targetPort: 5432
  selector:
    app: {{ .Release.Name }} # This selects the pod(s) that match the selector
  type: ClusterIP